Rails.application.routes.draw do
  get 'novells/index'
  get 'novells/show'
  get 'novells/new'
  get 'novells/create'
  get 'novells/update'
  get 'novells/edit'
  get 'novells/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'genres/index'
  get 'genres/show'
  get 'genres/new'
  get 'genres/create'
  get 'genres/update'
  get 'genres/edit'
  get 'genres/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :genres
  resources :publishers
  resources :novells
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
